name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45cca749b802543e5226bce1d096ab4d38b5de6c5930d9cc324f919bc638e157"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
