name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34fbefbc1a7243f6659ccd00686dedae4c9366a22a201f9b8b14a4416ec65023"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
