name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3591d0d3b3da47a41f5371b2c04c55d7acde69a1b106c8d0358c460cb6302b34"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
