name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eff6b11d9508eee2fc067e9bcefeedd1d5371592fd757a65740f9cc20538dbb"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
