name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7933ef25b47120f1c2c291af79dbe9582c697b40e0ec6da712149877aca8f162"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
