name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bba05eead6e0e1bb0b0914a1265109f7f29dd17bae2f74cad92085c1283691e"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
