name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5302718c7796428c690ac574b48ffeea3c013ae2b2ec224aa85913dbb64cbad"

[versions]
fabric = "0.16.7"
minecraft = "1.20.4"
