name = "DeckCraft"
author = "UltraStorm"
version = "1.1.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ec110224a101962f8bb5cdb97fbd88c74756b50bb69003a9aff47fdbf199c61"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
