name = "DeckCraft"
author = "UltraStorm"
version = "1.0.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fbe6563d64e75aec840c4d4c4cf4b74b5d58430b7165b318f373b8a7d53620e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
