name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "281e3f300faab49d9c0caa04dd9704c4f79071a64ff0b669f56a03222948c25d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
