name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29037f9d0be56e42b739c8f3b0c4af8f37e02d14de103ba8bccdfa4599a470ce"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
