name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9983fa84b911e719df00bcdbf5ae33081f8fe664e3d87b2c3fe7c809c38214b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
