name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4746b864efdbb94e244e32ea2f7bae48db02279780790db339612cc1b4713a11"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
