name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d227fbed3ba87883422d9dba513bb8796b53c0ef608c192e061269cbeabc39d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
