name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a82abc2661dc1b68f445121677bb0741183d1bb875f1c290718b418595715e3a"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
