name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36aa893b131bd1f60020650199005f2d5b3f287bd49c39e9a9ddac8c7377443f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
