name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d92f0e017eacf054d029d5a14f2c7d81f42a9a130666ed39843b6f2ec33f96f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
