name = "DeckCraft"
author = "SkywardMC"
version = "2.1.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf9a3704b63b3d212ab874bbd32b57b2ec35e763a2e19433553e5d108434b993"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
