name = "DeckCraft"
author = "SkywardMC"
version = "2.1.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "423efc269413006397c0802b08cc2ae6af392fc5a7f6f7ad5a0fda118d2b208b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
