name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6701194c7390a94c65a176f6bf364f7c5024d4a32d21da69705d9c7187c094be"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
