name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b02a0a4b3f2afc2d302f0a0a92af18bcab5a501cb19a15f3dc71d1b14dc727b4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
