name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9da5d305805f59f47e878e99000162ebe2b9bff3633a2a702860c0587bad919b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
