name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "437eb7e94386d34792c1783d561f566f19835d5cd4a4ee1942e3de3a963ca555"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
