name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b7183fb868876cabd37c5f99b1c1b0406faeeb4e959dcc1187faca3dbd75f85"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
