name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceb5694c01716cb7e85ec1eef6b8bd703c06778a89cf35c7a1582a6f79fe069e"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
