name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f26d9637490b18ab7e941ff784a142e8a23a5966ba808b095df170c75553c477"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
