name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a16a48841567c04c84d1d167dd673767a58ae5b613b7126ac03e83e9d04b310"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
