name = "DeckCraft"
author = "SkywardMC"
version = "2.7.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7ee9cd243227c0542690f819813e7ebd5eb76a334171c4f5f8fc8e60fac4dc"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
