name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99d9455d97af2e544521a09ecd5812c4716a3831d3e8f70f5a1a6c3d945b4f70"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
