name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bf873dd93f4ecda7625a45919dc5f77d3c261060eebafe9c182dd8dca331420"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
