name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "963210205a7a6d9a602829087ffdda12af24980f6a3f50f4e4fb7d0a5afc3e63"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
