name = "DeckCraft"
author = "UltraStorm"
version = "1.1.0+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2204d4767bd57b1c4a65d8433a7b93265973d68ee928f15007f3fddc58f0faa5"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
