name = "DeckCraft"
author = "UltraStorm"
version = "1.0.0+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28deafb7c88f4ef0022a23a0b4d8ce65184457903945641ba38296f198508dfd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
