name = "DeckCraft"
author = "SkywardMC"
version = "2.1.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de9047df1679b348dba10c76631bf05f805b049bf384fe785ef692447d26e2b0"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
