name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e7fe52e6e70df72602819cda0e9e7135ac5d3b133b43d627d4b03364cccbdd3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
