name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2589750c625169d0af3ab75b1bca3371752202eda5011e698900a03bb881caff"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
