name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef757ac2520c9b987352c61ebca6f13e2573039ead74335d5517aae3b3313e04"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
