name = "DeckCraft"
author = "SkywardMC"
version = "2.1.1+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4852935adc4d6c52655fe4805a40c0ad148c4a877b7cd0c56f4e5f11d09586c"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
