name = "DeckCraft"
author = "SkywardMC"
version = "2.0.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3c9f5b6097bee958ba136f729a3e98fab46d7d4b8d8e90c1397f9a2291a7cfd"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
