name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f711ba5c7d5ebfe5a2a2357400b093de140e179257352dc240ed1044c317e25"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
