name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30a744ea216efff6892ae6696462fdf05fcc799111ce9a89b95e665a04093026"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
