name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc3b504427d654fa343f65a6e33ea2fe02ef34f580d359d571d8ae3c6a0300c2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
