name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "209c00056d67c4427c6a2c478b80d000e0f56a7fe4dedc0aae4c071a7173bdac"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
