name = "DeckCraft"
author = "SkywardMC"
version = "2.0.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f1136b103b5e874ccfab302e69905cf32f716dd5abc3fe8ed12a21cdef88fa4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
