name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c949e012230343e83465ee7a95feb60ef8e9d888cfe4f438d6e48afcf6c4df14"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
