name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a7137c6b29b06f2b1c3311fcd3082b3465f71809c4b41d40cdf4e92436dcf41"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
