name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c0771186cdd3174b5ce29a952a607d8cdaa9483bf37b9b62853b12aa28e123"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
