name = "DeckCraft"
author = "SkywardMC"
version = "2.4.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37fdebbcb06bee9ecb91e9857d59f2efc3f89821cefad386881aac77949333ea"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
