name = "DeckCraft"
author = "SkywardMC"
version = "2.1.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3be0e185c42b1c5baa711a6dbe1d90791d114806cbf5857ae9fd90752bb1bd10"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
