name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "114791e8559600ce249b89fea4a45e1c63fbfedad4cbe43a3ea227423b2c02ea"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
