name = "DeckCraft"
author = "UltraStorm"
version = "1.3.1+1.19.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "642599cea9688238a4e5ab4191af016b846ba9354bfd6d96b3b4025bc61a09e1"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
