name = "DeckCraft"
author = "UltraStorm"
version = "1.2.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc6491f528d8565c4868064f92d5bd33a7c7da8ddd7dc92bf8237e3fb9dfa781"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
