name = "DeckCraft"
author = "UltraStorm"
version = "1.0.2+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bfac2ed2fd501357dc0ff51236e7b00b9d6b15662cfbdd3bfab8330d6be4ed5"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
