name = "DeckCraft"
author = "UltraStorm"
version = "1.0.1+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3785cb31a4f66d9bde9f9b24bdd54a34d1bfc731d4040df0c70ad20188ff40e"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
