name = "DeckCraft"
author = "UltraStorm"
version = "1.0.0+1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3c7ce2c117706fac2674f746bdb01aeb14cbb3c0c52abe7e42b16c3d58052a2"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
