name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c8ec1aa3b57f96059a1dd602923efe262764e9dec583e614e9f3cbd1d8cd338"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
