name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24e8c9228a73d820d75b53afedaee1bb3524ba8a4fb7178a188fa5ec54191247"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
