name = "DeckCraft"
author = "SkywardMC"
version = "2.0.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbebb68583240431a222039ca90a97d45e16d9990d57909652a70a705e6e8983"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
