name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9ca4a23644b7ebb3b422e3b8fe5dbd4f570aed8e30cb36b1d5f986781a603c5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
