name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db21936f53e3d606042c3fc7457831a025a0ee0a4ca5985f25538dd259eadbaa"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
