name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a581eaae3f2560279ae904038d3bdfff962f8bb5a83c2da7aa9a7754ea5b8bfe"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
