name = "DeckCraft"
author = "SkywardMC"
version = "2.1.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6745f4f8e172533e972abcf623aab02d8234372fdb009a5b71f13a9092ccc2f"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
