name = "DeckCraft"
author = "SkywardMC"
version = "2.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f3203e7943160905e2c0b69453fb0137ed73a0a123d154c506ee51113f282f9"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
