name = "DeckCraft"
author = "SkywardMC"
version = "2.1.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d50a861c1a05e2b2575ba03acc0d3b42cb66b66e672327316b400996719c44c"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
