name = "DeckCraft"
author = "SkywardMC"
version = "2.6.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b116a4bb49ec402d6799a65a45b5b33c47f873ccc9b9b051059ac5cef36ab128"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
