name = "DeckCraft"
author = "SkywardMC"
version = "2.3.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f67148ad6e8632c84dbd33fdfa76913177b40b3beee50397e39649feebf8956b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
