name = "DeckCraft"
author = "SkywardMC"
version = "2.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "661a2b3ba5097098237027347359fefe1dea26dda1b68c60432dab605604c97a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
