name = "DeckCraft"
author = "SkywardMC"
version = "2.1.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbc8be5c71e53cc4742eb825efabcbeee0a23d1880189f7d00624a45d73bd7ef"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
