name = "DeckCraft"
author = "SkywardMC"
version = "2.2.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad954402eb7d068cf1ff01b6d0624b0bdec83455e61ef692335ea70704fdac37"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
