name = "DeckCraft"
author = "SkywardMC"
version = "2.0.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7043367c5bd3dfbd7e3264a8b489207a71818b45da3394cc3443fd432da41625"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
