name = "DeckCraft"
author = "SkywardMC"
version = "2.5.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be696849c1770823b28bf1ce72c73606bbe55118ab490020d1b7709fba1f69d6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
