name = "DeckCraft"
author = "SkywardMC"
version = "2.5.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1481ffcb93ec135257795c93cf21057ef23d8a30eed8f96d8fe5c109a87399e"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
