name = "DeckCraft"
author = "quatquatt"
version = "1.3.2+1.20.1.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af878edfe3c98013627723714ae87495c8f8a3398ec3bef8a3af0d1362c813ff"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
