name = "DeckCraft"
author = "UltraStorm"
version = "1.0.0+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "154d85bd525a6bffacaa88313ca1832182cb24b3ad10cc232f00b483fae45265"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
