name = "DeckCraft"
author = "UltraStorm"
version = "1.0.0+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aacf5b74d3512575c4b84a08ed77f49bfbfb1b087d60bc02bbbd4743e7e670ed"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
